name: "Publish docker image"
description: "Build and push artifacts to the Docker registry"
inputs:
  registry-username:
    description: "Username for image registry"
    required: true
  registry-access-token:
    description: "Access token for image registry"
    required: true
  docker-registry:
    description: "Docker registry"
    required: false
    default: "ghcr.io"
  context-path:
    description: "Build's context path"
    required: false
    default: "."
  dockerfile-path:
    description: "Path to the Dockerfile"
    required: false
    default: "./Dockerfile"
  platforms:
    description: "List of target platforms for build"
    required: false
    default: "linux/amd64,linux/arm64"

runs:
  using: composite
  steps:
    - name: 🏗 Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: 🏗 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 🔓 Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-access-token }}

    - name: ℹ️ Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.docker-registry }}/${{ github.repository }}
        tags: |
          type=sha
          type=ref,event=branch,enable=${{ contains(github.ref_name, 'epic') }}

    - name: 🚀 Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
